modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"
issueTrackerURL = "https://github.com/DawsonBodenhamer/Adorable-Hamster-Pets-1.21/issues"

[[mods]]
modId = "adorablehamsterpets"
version = "${version}"
displayName = "Adorable Hamster Pets"
authors = "The Scarlet Fox"
description = '''
Sure, you’ve got dragons and machines, but let’s be honest— no respectable mod pack is complete without tiny fluffy hamsters running around.
'''
logoFile = "assets/adorablehamsterpets/icon.png"

[entryPoints]
main = "net.dawson.adorablehamsterpets.forge.AdorableHamsterPetsForge"

[[dependencies.adorablehamsterpets]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.adorablehamsterpets]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.adorablehamsterpets]]
modId="architectury"
mandatory=true
versionRange="[9.2.14,)"
ordering="AFTER"
side="BOTH"

[[dependencies.adorablehamsterpets]]
modId="geckolib"
mandatory=true
versionRange="[4.4.9,)"
ordering="NONE"
side="BOTH"

[[dependencies.adorablehamsterpets]]
modId="fzzy_config"
mandatory=true
versionRange="[0.7.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.adorablehamsterpets]]
modId="jade"
mandatory=true
versionRange="[11.7.0,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config = "adorablehamsterpets.mixins.json"