modLoader = "javafml"
loaderVersion = "[2,)"
license = "All Rights Reserved"
issueTrackerURL = "https://github.com/DawsonBodenhamer/AdorableHamsterPets-Public/issues"

[[mods]]
modId = "adorablehamsterpets"
version = "${version}"
displayName = "Adorable Hamster Pets"
authors = "The Scarlet Fox"
description = '''
Sure, you’ve got dragons and machines, but let’s be honest— no respectable mod pack is complete without tiny fluffy hamsters running around.
'''
logoFile = "assets/adorablehamsterpets/icon.png"

[entryPoints]
main = "net.dawson.adorablehamsterpets.neoforge.AdorableHamsterPetsNeoForge"

[[dependencies.adorablehamsterpets]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.172,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.adorablehamsterpets]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.adorablehamsterpets]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.adorablehamsterpets]]
modId = "geckolib"
type = "required"
versionRange = "[4.7.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.adorablehamsterpets]]
modId = "fzzy_config"
type = "required"
versionRange = "[0.6.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.adorablehamsterpets]]
modId = "jade"
type = "required"
versionRange = "[15.9.3,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "adorablehamsterpets.mixins.json"