name: Build & Publish Mod

# This workflow builds the mod and publishes it to Modrinth and CurseForge
# when a new tag matching the pattern v* is pushed.  It runs on the
# develop branch (1.21.1) and is duplicated on the 1.20.x
# branch with different loader/glob values.

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Capture the tag name as an environment variable for extraction
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Build jars
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Derive version without leading v
        id: vars
        run: |
          V="${VERSION#v}"
          echo "V=$V" >> $GITHUB_OUTPUT

      - name: Download CHANGELOG.md from public repo
        run: |
          curl -fL "https://raw.githubusercontent.com/DawsonBodenhamer/AdorableHamsterPets-Public/main/CHANGELOG.md" -o CHANGELOG.md

      - name: Extract changelog for this version
        shell: bash
        run: |
          # Strip the leading 'v' from the tag if present
          V="${VERSION#v}"
  
          # Grab everything after '## [<version>]' until the next '---' separator
          # Match headings/separators with optional leading spaces and trim leading spaces.
          awk -v ver="$V" '
            $0 ~ "^[[:space:]]*## \\[" ver "\\]" {p=1; next}
            p && /^[[:space:]]*---/ {exit}
            p {
              sub(/^[[:space:]]+/, "")
              print
            }
          ' CHANGELOG.md > release_changelog.md

          echo "Extracted changelog for version $V:"
          sed -n '1,120p' release_changelog.md

      - name: Publish Fabric/Quilt version
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: LmrhZdK2
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 1306061
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          # Version name for Modrinth/CurseForge
          version: ${{ steps.vars.outputs.V }}-1.21.1+fabric
          version-type: beta

          # EXACT file path + name produced by Gradle build
          files: fabric/build/libs/adorablehamsterpets-${{ steps.vars.outputs.V }}-1.21.1+fabric.jar

          # Fabric/Quilt dependencies for Modrinth
          modrinth-dependencies: |
            fabric-api(required)
            architectury-api(required)
            geckolib(required)
            fzzy-config(required)
            fabric-language-kotlin(required)
            modmenu(optional)
            jade(optional)

          # Fabric/Quilt dependencies for For CurseForge
          curseforge-dependencies: |
            306612(required)
            419699(required)
            388172(required)
            1005914(required)
            308769(required)
            308702(optional)
            324717(optional)

          changelog-file: release_changelog.md
          loaders: |
            fabric
            quilt
          game-versions: 1.21.1

      - name: Publish NeoForge version
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: LmrhZdK2
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 1306061
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          # Version name for Modrinth/CurseForge
          version: ${{ steps.vars.outputs.V }}-1.21.1+neoforge
          version-type: beta

          # EXACT file path + name produced by Gradle build
          files: neoforge/build/libs/adorablehamsterpets-${{ steps.vars.outputs.V }}-1.21.1+neoforge.jar

          # NeoForge dependencies for Modrinth
          modrinth-dependencies: |
            architectury-api(required)
            geckolib(required)
            fzzy-config(required)
            kotlin-for-forge(required)
            jade(optional)

          # NeoForge dependencies for For CurseForge
          curseforge-dependencies: |
            419699(required)
            388172(required)
            1005914(required)
            351264(required)
            324717(optional)

          changelog-file: release_changelog.md
          loaders: neoforge
          game-versions: 1.21.1