name: Build & Publish Mod

# PURPOSE:
# Builds both Fabric/Quilt and Forge jars and publishes them to Modrinth and CurseForge.
# TRIGGER:
# - Automatically runs when a lightweight tag like "v3.1.0" is pushed.
# - Can also be run manually via the "Run workflow" button (workflow_dispatch).
#
# NOTE:
# - This file is for 1.20.x line. For 1.21.1, an alternate version of this file exists.
# - Do NOT put comments inside the dependency lists (the lines after a "|"), as they are literal blocks.

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Capture the raw tag name, e.g. "v3.1.0" as an environment variable for extraction
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      # 1) Get source at the tagged commit
      - name: Check out code
        uses: actions/checkout@v4

      # 2) Java toolchain for Gradle/loom
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # 3) Build both subprojects (fabric, forge). Output jars end up under each module's build/libs
      - name: Build jars
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      # 4) Strip the leading "v" to reuse the numeric version in file names & labels
      - name: Derive version without leading v
        id: vars
        run: |
          V="${VERSION#v}"
          echo "V=$V" >> $GITHUB_OUTPUT

      # 5) Pull the public changelog (kept in a separate repo) into the workspace
      - name: Download CHANGELOG.md from public repo
        run: |
          curl -fL "https://raw.githubusercontent.com/DawsonBodenhamer/AdorableHamsterPets-Public/main/CHANGELOG.md" -o CHANGELOG.md

      # 6) Extract only the section for this tag from the changelog
      #    Logic:
      #    - Find "## [<version>] ..." line
      #    - Capture everything after it until the next line that is exactly "---"
      #    - Be tolerant of leading spaces on headings/separators and trim them in output
      - name: Extract changelog for this version
        shell: bash
        run: |
          # Strip the leading 'v' from the tag if present
          V="${VERSION#v}"
  
          # Grab everything after '## [<version>]' until the next '---' separator
          # Match headings/separators with optional leading spaces and trim leading spaces.
          awk -v ver="$V" '
            $0 ~ "^[[:space:]]*## \\[" ver "\\]" {p=1; next}
            p && /^[[:space:]]*---/ {exit}
            p {
              sub(/^[[:space:]]+/, "")
              print
            }
          ' CHANGELOG.md > release_changelog.md

          echo "Extracted changelog for version $V:"
          sed -n '1,120p' release_changelog.md

      # 7) Publish Fabric/Quilt build to Modrinth & CurseForge
      #    - Uses exact jar path produced by the build (keeps naming scheme intact)
      #    - Attaches dependencies per platform
      #    - Attaches extracted changelog snippet
      - name: Publish Fabric/Quilt version
        uses: Kir-Antipov/mc-publish@v3.3
        with:

          # Project identifiers and API tokens
          modrinth-id: LmrhZdK2
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 1306061
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          # Human-visible version name for Modrinth/CurseForge
          version: ${{ steps.vars.outputs.V }}-1.20.1+fabric
          version-type: beta

          # EXACT jar  file path + name produced by Gradle build (fabric module)
          files: fabric/build/libs/adorablehamsterpets-${{ steps.vars.outputs.V }}-1.20.1+fabric.jar

          # Fabric/Quilt dependency slugs for Modrinth (no comments allowed inside the block)
          modrinth-dependencies: |
            fabric-api(required)
            architectury-api(required)
            geckolib(required)
            fzzy-config(required)
            fabric-language-kotlin(required)
            modmenu(optional)
            jade(optional)

          # Fabric/Quilt dependency IDs For CurseForge (no comments allowed inside the block)
          curseforge-dependencies: |
            306612(required)
            419699(required)
            388172(required)
            1005914(required)
            308769(required)
            308702(optional)
            324717(optional)

          # Attach the changelog snippet that was extracted above
          changelog-file: release_changelog.md

          # Mark as Fabric & Quilt, and target the correct MC version
          loaders: |
            fabric
            quilt
          game-versions: 1.20.1

      # 8) Publish Forge build to Modrinth & CurseForge
      #    - Same approach as Fabric, but with Forge jar and its dependencies
      - name: Publish Forge version
        uses: Kir-Antipov/mc-publish@v3.3
        with:

          # Project identifiers and API tokens
          modrinth-id: LmrhZdK2
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 1306061
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          # Human-visible version name for Modrinth/CurseForge
          version: ${{ steps.vars.outputs.V }}-1.20.1+forge
          version-type: beta

          # EXACT jar file path + name produced by Gradle build (forge module)
          files: forge/build/libs/adorablehamsterpets-${{ steps.vars.outputs.V }}-1.20.1+forge.jar

          # Forge dependency slugs for Modrinth (no comments allowed inside the block)
          modrinth-dependencies: |
            architectury-api(required)
            geckolib(required)
            fzzy-config(required)
            kotlin-for-forge(required)
            jade(optional)

          # Forge dependency IDs for CurseForge (no comments allowed inside the block)
          curseforge-dependencies: |
            419699(required)
            388172(required)
            1005914(required)
            351264(required)
            324717(optional)

          # Attach the changelog snippet that was extracted above
          changelog-file: release_changelog.md

          # Mark as Forge and target the correct MC version
          loaders: forge
          game-versions: 1.20.1